import { Fragment } from 'react';
import Head from 'next/head';


export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/05e016c845.js" crossorigin="anonymous"></script>
      </Head>
      <h1>Hi</h1>
    </Fragment>
  )
}
