import { Fragment, useState } from 'react';
import Head from 'next/head';
import Cards from '../components/Home/Cards';
import Carousel from '../components/Home/Carousel';

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://kit.fontawesome.com/05e016c845.js" crossOrigin="anonymous"></script>
      </Head>
      <div className="relative overflow-x-hidden">
        <Carousel />
      </div>
      <Cards />
    </Fragment>
  )
}
